export interface Nota {
  slug: string;
  title: string;
  subtitle?: string;
  author?: string;
  category: "vida" | "obras" | "testimonios" | "maria" | "grupos";
  content: string[];
  images: string[];
}

export const NOTAS: Nota[] = [
  // ═══════════════════ VIDA ═══════════════════
  {
    slug: "jorge-ninez-y-adolescencia",
    title: "Jorge, niñez y adolescencia",
    author: "Marta Gandur de Brito",
    category: "vida",
    content: [
      'En Jorge se cumplió la palabra de Jeremías que relata en su libro al referir su vocación "el Señor me dijo: antes de que salieras del seno de tu madre, yo te había consagrado".',
      "Fue bautizado en Catamarca a los 2 años, cumpliendo la promesa de mi padre de que, si era varón, en el santuario de la Virgen del Valle seria bautizado.",
      "A los seis años hizo de pastorcito en la procesión de la Virgen de Fátima, parroquia a la que pertenecíamos.",
      "Recibió la primera Comunión en el Colegio del Sagrado Corazón, donde cursó la primaria y parte de la secundaria. En tercer año pasó a la Escuela de Comercio, que era mixto.",
      "En un tiempo en que nuestro padre -que era distribuidor mayorista de bebidas- se enfermó, Jorge, en una camioneta, se encargó del despacho de bebidas y sus tareas propias, cargar, acarrear, cobrar.",
      "Recuerdo que gustaba de una compañera, era amado y querido por todos. Tuvo su fiesta cuando cumplió 18 años.",
      "Se fue de vacaciones con un amigo, periodo en el que conoció a una joven, le contó a mi mamá, estaba entusiasmado, incluso le quería regalar un anillo, pero después todo quedó en la nada.",
      "Fue presidente de la Acción Católica de la parroquia de Fátima hasta que ingresó al seminario.",
      "Tenía todo lo que un joven podía querer. Cuál sorpresa para todos cuando dijo que quería ser sacerdote. El más impactado fue nuestro padre, que tenía ilusiones de que él siguiera con el negocio.",
      "Apoyamos a Jorge guardando silencio. Por eso cursó el primer año como externo en el seminario.",
      "Ya viviendo en el seminario, siendo diácono, iba los fines de semana a Famaillá. Cuando se ordenó de sacerdote comenzó a formar un grupo de jóvenes en esa ciudad, de allí salieron algunas vocaciones para el sacerdocio y la vida religiosa.",
      "Mi padre lo acompañaba a distintas capillas los fines de semana, y cantaba con su guitarra.",
      "Nuestro padre, en sus últimos días, dijo al padre Parrado que le administró los sacramentos:",
      '"Yo creí perder un hijo, y lo gané para siempre".',
    ],
    images: ["niñez2.jpg"],
  },
  {
    slug: "una-vocacion-del-padre-gandur",
    title: "Una vocación del Pbro. Jorge Antonio Gandur",
    author: "Padre Carlos Torres",
    category: "vida",
    content: [
      "Conocí al padre Jorge cuando tenía 7 años cuando estaba en la catequesis recuerdo que todos los sábados nos iba a visitar a la catequesis y nos hacía preguntas y también bromas. Siempre fue una persona que supo conjugar la seriedad y el buen sentido del humor. Con el paso del tiempo empecé a ayudarle en misa en la sede parroquial. Algunas veces, nos pedía a los monaguillos que le acompañemos a otras capillas y con mucha ilusión íbamos, en el camino rezábamos El Rosario o él nos contaba alguna anécdota pastoral creo que ese estilo poco a poco fue despertando en mí la pregunta: ¿por qué no ser sacerdote?",
      "En mi juventud recuerdo las meditaciones de los miércoles antes de la misa y fue ahí cuando comencé a sentir fuerte la inquietud vocacional razón por la cual me acerqué a hablar con él y me dijo que sería bueno que iniciara un discernimiento con un sacerdote que estaba en la parroquia, a pesar de que él no fue mi director espiritual siempre estuvo atento al proceso e incluso cuando ingresé al seminario.",
      "Lo que más admiraba del padre Jorge fue su celo apostólico, el darse tiempo para visitar e interesarse por las necesidades de cada comunidad, su amor a la Eucaristía y a la Virgen, como así también el interés y preocupación por los sacerdotes, creo que todo ello hablaba de su amor a Dios y al sacerdocio. Para los que hemos podido conocerlo de cerca, ha sido una persona que supo estar con todos sin importar la clase social. Además, siempre apostó por la formación integral de cada \"parroquiano\" tanto espiritual (con retiros, meditaciones) como así también humana (comedores, cursos de capacitación, escuelas).",
      "Lo que me queda por decir es darle gracias a Dios por el don de la vida del padre Jorge porque así cómo él y muchos otros, me ayudó a crecer como creyente y también en lo vocacional.",
    ],
    images: ["vocacion1.jpg", "sacerdote8.jpg", "vocacion2.jpg"],
  },
  {
    slug: "en-memoria-del-padre-jorge-gandur",
    title: "En memoria del Padre Jorge Gandur",
    author: "Pbro. Lic. Horacio A. Gómez",
    subtitle: "Párroco de Nuestra Señora de La Caridad",
    category: "vida",
    content: [
      "En el año 1976, cuando fui al seminario de Tucumán a averiguar los requisitos para ingresar, me encontré con un joven de sotana que me recibió con mucha alegría, como quien va a comprarle algo, y él por su parte me ofrecía su maravillosa mercancía.",
      "La impresión que tuve del entonces seminarista, Jorge Antonio Gandur, fue de estar ante un joven con un espíritu arrollador que, a mi parecer era, ni más ni menos que el de un corazón enamorado de Jesús.",
      "Al mismo tiempo, en esa oportunidad y en muchas otras, percibí que ninguna persona con la que Jorge se encontraba le era indiferente en su situación particular y siempre recibía de Gandur, una visión bien sobrenatural, pero con sentido común.",
      "El gran fruto de mi encuentro con Jorge fue que me enseñó a no centrarme en los lógicos temores ante tamaña decisión, sino más bien a poner toda mi confianza en Jesucristo.",
      "Posteriormente, aunque nuestra amistad fue creciendo de una manera discontinua, descubría en él un sacerdote centrado en Cristo y, sobre todo en la Sagrada Eucaristía. Cultivaba una intensa vida de oración y vivía su ministerio con muy buen humor.",
      "A veces me invitaba a acompañarlo a rezar el rosario o el breviario o a hacer un rato de oración mental. Allí fue donde descubrí, y con el tiempo lo confirmé, de dónde sacaba la fuerza que lo animaba a enfrentar los desafíos de las distintas vicisitudes de su vida, que no fueron pocas ni fáciles.",
      'La Sagrada Escritura indica que "la memoria del justo perdurará en el tiempo"(Salmo 112, 6). Por eso soy testigo de la fuerza y el dinamismo con el que vivía intensamente su sacerdocio y la luz que ha dejado, para siempre, en muchas personas.',
      "El padre Eduardo Arnau decía que Dios lo llevó al padre Jorge a su presencia, a la vida eterna, antes de tiempo, porque había cumplido con celeridad con todo lo encomendado en esta vida.",
      "A 10 años de su partida, su recuerdo continúa en nuestra memoria: sus dichos, sus ejemplos, su buen humor, y la marca que dejó no sólo en sus obras materiales sino, sobremanera, en el paso de su acción apostólica por los corazones de quienes lo hemos tratado.",
      "En esta publicación se reúnen los testimonios de algunas personas que trabajaron junto al Padre Jorge en sus aventuras pastorales, siendo consciente que hace falta escribir un libro de varios tomos para mostrar algo de la gran personalidad del Padre Jorge Gandur.",
      "En este trabajo hemos contado con el invalorable aporte del Profesor Fernando Casiva y de la Comisión que he constituido con motivo de esta publicación y de los actos conmemorativos de la semana del 21 al 26 de Agosto de 2023.",
      "Seguramente nos hemos quedado cortos, como dije, en la recolección de testimonios, pero al menos estos nos servirán de recuerdo y homenaje a ese hombre Dios que trabajó incansablemente por el Reino de los Cielos. A la vez que lo recordamos, le pedimos que nos siga cuidando desde la Casa del Padre.",
    ],
    images: ["sacerdote1.jpg", "vocacion2.jpg", "caridad3.jpg", "vocacion1.jpg"],
  },

  // ═══════════════════ OBRAS ═══════════════════
  {
    slug: "la-llegada-del-padre-jorge-a-la-caridad",
    title: "La llegada del Padre Jorge a La Caridad",
    author: "Ricardo A. Aversano",
    category: "obras",
    content: [
      "Para dimensionar el impacto de la llegada del Padre Jorge a la Capilla Nuestra Señora de la Caridad, necesariamente debemos recordar cómo era atendida en esa época. Las celebraciones de la Santa Misa en la Capilla fueron atendidas durante mucho tiempo por los Presbíteros Dionisio Fuentes, Silvio Medina y Vitalino Treco, que colaboraron activamente en la atención espiritual de los fieles de la zona. La decisión del Arzobispado de erigir la Parroquia Nuestra Señora de la Caridad y San Antonio fue muy acertada a fin de dar un fuerte impulso a la presencia de la Iglesia en la zona norte de Yerba Buena.",
      "La impronta y la personalidad del Padre Jorge marcarían a fuego las características de esta porción del Pueblo de Dios. Su potente vozarrón entonando el Gloria o Cantemos al Amor de los Amores, comenzó a resonar por las calles del barrio, y aún hoy se recordamos su eco.",
      'Podemos decir de él que era un niño en envase grande. A algunos les parecía un poco "Loco" y "Arrebatado", pero en realidad era un hombre simple, siempre pensando en grande, totalmente desinhibido. Estaba a cualquier hora en todos los lugares donde se lo necesitaba, siempre muy cercano. Llegaba a un lugar y enseguida conquistaba a la gente con su cercanía y ocurrencias.',
      'Sabía todo y estaba en todo, y además lo podríamos calificar como un excelente "pedigüeño de Dios", buscando en las casas de los feligreses, todo lo que le sirviera para engalanar las Capillas. Su llegada representó para muchos la apertura de las puertas de la Parroquia, con su cercanía a las familias y su costumbre de compartir acontecimientos familiares y de la Parroquia. Cuando llegaba a casa nunca quería comer mucho porque "estaba a dieta", pero empezaba con sólo una fruta y terminaba con fideos o asado.',
      'Su prédica sobre que "Siempre lo mejor para Dios" y "Primero amigo de Dios para poder ser amigo de los hombres" caló profundo en muchos de los feligreses.',
      "Fue un adelantado de las enseñanzas que impulsa hoy el Papa Francisco: desarrolló lo que en ese momento era la periferia de Yerba Buena, y es así que fuimos testigo de las Piedras Fundacionales de las Capillas Divina Misericordia y Divino Niño. Dijo NO al Clericalismo, su criterio era dejar hacer al Laico, dar libertad para llevar adelante los Retiros y comprometer su presencia en los mismos.",
      'Se puso al hombro los cimientos y las cuatro paredes de la vieja construcción que pretendía ser una Casa de Retiros y la convirtió en "Betel". Expandir la Iglesia de Cristo era su obsesión, y así nació también la Capilla Nuestra Señora del Rosario de San Nicolás.',
      "Pero hablar de él sin hablar de su GRAN AMOR deja todo incompleto: No habríamos dicho nada del Padre Jorge si no mencionamos su AMOR por ¡LA EUCARISTÍA!!! Esto es lo que más caló en muchos de los que lo conocieron. Esto es lo que dio origen al \"Templo de Adoración Perpetua\" y los Adoradores.",
      "La visión que transmitió el Padre Jorge",
      "La prédica de ¡Nada de estériles lamentos! y de ¡Dar la vida! fue muy fuerte en esa etapa de la vida parroquial.",
      "Tenía una visión muy acertada de la Vocación de quienes estaban cerca suyo, se lo decía con toda claridad. A muchos de los jóvenes, que tenían un servicio concreto en la Parroquia, los acompañó en la transición de la pubertad a la juventud y a la adultez.",
      "Pilar Izquierdo, Mocho Sario, Lelia de Martínez, Quelo Romero, José Canigia, David Coronel y Luis Alvarez fueron algunos \"locos\" que supieron acompañarlo, y seguramente, tanto Pilar como el Mocho hoy estarán gozando junto al Padre Jorge en la Casa del Padre.",
      "Los frutos de ese momento...",
      "Desde su llegada se verificó un importante acercamiento de gente a la Iglesia, porque se sintió acogida y sostenida espiritualmente.",
      "No se puede pasar por alto su especial dedicación a los demás sacerdotes, especialmente al atravesar alguna crisis o incluso alejarse de su ministerio. A muchos de ellos supo congregarlos y acompañarlos en la vivencia de las crisis personales.",
      "Florecieron diferentes actividades que nuclearon a jóvenes y familias, entre las que podemos mencionar a:",
      'El "Festival Navideño" que se inició con el objetivo de "Celebrar Juntos el Nacimiento del Redentor" y que en un año en particular logró celebrar la Cena de Navidad en la Capilla.',
      'El "Festival de la Vida y por la Vida", realizado en el Club Caja Popular con la presencia de 10 grupos musicales entre los que se destaca a Los Tekis y a Los Alonsitos, totalmente organizado por los jóvenes de la Capilla.',
      'El "Vía Crucis", desde el Cristo hasta la Capilla.',
      'Los "Retiros Espirituales".',
      "Por sus frutos los conocerán…",
      "En las Parroquias de Yerba Buena y en todas las Capillas nos encontramos con gente que se acercó a la Iglesia en la época en que el Padre Jorge impulsaba las actividades.",
      "Muchos Matrimonios y Familias viven hoy su Vida Sacramental gracias al sostén que el Padre Jorge logró durante su presencia entre nosotros.",
      "Pero a mi criterio, el fruto más acabado de su tarea en nuestro tiempo y que queda como su legado es la presencia y continuidad de los Adoradores.",
    ],
    images: ["caridad1.jpg"],
  },
  {
    slug: "la-capilla-y-el-colegio-divina-misericordia",
    title: "La capilla y el colegio divina misericordia",
    author: "María Soria de Sandoval",
    category: "obras",
    content: [
      "En el año 1993 comienza a gestarse a través de las Señoras de Acción Católica de la Parroquia Nuestra Señora de la Caridad, en sus visitas domiciliarias en el Barrio Nicolás Avellaneda IV, la necesidad de la presencia del Señor en dicho barrio.",
      "Desde el año 1994 se comienza a gestionar la donación de los 10 terrenos destinados a recreación y asistencia social de la comunidad para el Arzobispado de Tucumán, para construir la Capilla y por ende centros de Ayuda o recreación para el Barrio.",
      "Con la llegada del padre Jorge Gandur, en el año 1996, a quien conocía desde la escuela secundaria, se comienza a dar forma la planificación de la futura Capilla.",
      "Cuando nos encontramos, a su llegada, surgió la charla de mi hacer en la Parroquia en el área de Administración y Catequesis y también mi actividad de contadora en el ámbito privado. Este dato hizo que al poco tiempo me pidiera que lo ayudara a organizar la economía de toda la Parroquia junto a las personas que ya lo venían haciendo.",
      "Por ese entonces funcionaba, en lo que hoy son los salones de la Casa de Retiro en La Caridad, un comedor que atendía a los niños de los Barrios Nicolás Avellaneda 1, 2, 3 y 4. Me dijo que urgentemente debíamos construir salones en el Barrio Nicolás Avellaneda para trasladar allí el Comedor y terminar con el flagelo de que los niños vinieran caminando desde allí a buscar su plato de comida. Así lo hicimos, con bastante premura y llegamos a albergar 300 niños a la hora de comer. También en esos salones posteriormente se desarrollaron a partir de 1996 varios proyectos sociales financiados por el Banco Interamericano de Desarrollo. Al mismo tiempo hicimos una guardería que albergaba niños de 1 a 4 años.",
      "Mientras construíamos el Templo, los encuentros de Catequesis funcionaban en los salones del comedor. El día del niño acostumbrábamos a regalar el libro de los Evangelios a los pequeños alumnos de Primer año de Comunión. Un día el padre me preguntó cómo la llevaba con los libros que habíamos entregado y le contesté que no tan bien, porque la mayoría de ellos no sabían leer o apenas deletreaban. De ese pequeño diálogo, lo contaba él, le surgió la idea de construir un colegio en ese lugar.",
      "Es de destacar la acción rica y fructífera en esta Capilla, ya que las Comuniones y Confirmaciones eran las más numerosas de la jurisdicción parroquial. También era intenso trabajo de las Señoras de la Acción Católica y los grupos de jóvenes. Es de destacar que desde esta comunidad surgió la vocación sacerdotal del hijo, de quién fue la cocinera del comedor.",
      "Cuando estaba construida la Capilla con su sacristía y secretaría, hicimos los trámites para que un médico clínico atendiera en el Barrio 2 días a la semana, usando las instalaciones de la secretaría como consultorio. Un día fui a dejar una bolsa con medicamentos que nos donaban un grupo de farmacéuticos. Era invierno y estuve esperando en el atrio del templo unos 30 minutos. Hacía mucho frio. Le comenté el detalle al padre Jorge y eso le hizo nacer la decisión de construir un centro asistencial con sala de espera. El Centro asistencial Divina Misericordia funciona hoy debidamente equipado con 5 médicos de distintas especialidades, con su enfermería permanente de lunes a viernes.",
      "En el año 2009 el padre Jorge cumplió su deseo de inaugurar el Colegio Divina Misericordia creando en ese entonces el jardín de 4 años con la forma jurídica de Fundación, integrada por feligreses de la Parroquia. Así sucesivamente iban avanzando el jardín de 5 y los grados de Primaria.",
      "A fines del 2011 el padre comenzó con los problemas de salud que lo llevó a su partida a la casa del Padre el 13 de agosto del 2013.",
      "Cuando lo trajeron a Tucumán, desde Buenos Aires, días antes de su partida, fui a rezar con su hermana Anita en los pasillos del sanatorio y de pronto salió un enfermero y nos dijo que pasáramos. Anita entró e inmediatamente salió y me dijo: A vos te llama. Le pregunté: ¿El padre sabe que estoy? Y ella me respondió: El padre lo sabe todo.",
      "Entré, le tomé su mano y con la voz quebrada me dijo: No los abandones. Le pregunté: ¿A quiénes, padre? Me dijo: Al Colegio.",
      "Yo le hice una mueca de sorpresa y siguió diciendo: Muchos son los prodigios y mucho más los que vendrán. Asentí con mi cabeza y salí pidiéndole al Espíritu Santo que nos asistiera, ya que el Colegio, durante su enfermedad se vino abajo en lo económico y con muy pocos alumnos. Con la gracia de Dios, aquí estamos como Cooperativa de Trabajo Educativa de autogestión, con 223 niños en nivel inicial y primario, con un destacado personal docente y administrativo despidiendo este año la Sexta promoción de primaria con mucha alegría y con muy buen concepto en el Ministerio de Educación. En el Colegio somos conscientes que el padre intercede por nosotros desde el cielo.",
      "Tendría muchas más anécdotas para relatar en lo personal y muchas más de tantas otras personas de la Capilla que trabajaron a su lado y lo siguen haciendo hoy por la Gracia de Dios.",
      "El Padre Jorge Antonio Gandur fue sin duda un elegido de Dios. Una persona sensible, sutil, humilde y con una gran vocación de servicio hacia el prójimo.",
    ],
    images: ["divina1.jpg", "colegioDivina3.webp", "colegioDivina1.jpg", "divina3.jpg"],
  },
  {
    slug: "la-capilla-san-antonio-de-padua",
    title: "La Capilla San Antonio de Padua",
    author: "Armando y Chiné Nalim",
    category: "obras",
    content: [
      "Con agrado les dirijo a Ustedes algunos aspectos que se destacaron en el desempeño y distintas vivencias del Padre Jorge Gandur en sus años como primer Párroco de Nuestra Señora de la Caridad de Yerba Buena.",
      "Recuerdo con nostalgia y asombro la tarde en que fue puesto en el cargo por el entonces Arzobispo de Tucumán, Monseñor Ñañez durante la misa concelebrada en la capilla de San Antonio de Padua, sita en calle Romano y Pje. Usandivaras de Yerba Buena. En esa ocasión (que fue cuando lo conocí) el Padre Gandur estaba sumamente concentrado y absorto durante la misa, quizás un poco retraído.",
      "Pero luego, al transcurrir los días, se comenzó a notar y sentir su verdadera personalidad: fuerte, avasallante y decidida, ya que, desde mi vivienda, justo al frente de su casa, se podían escuchar a viva voz y a cualquier hora sus cánticos de alegría en el Señor y sus distintas manifestaciones personales con los vecinos.",
      'Con el Padre Jorge Gandur llegamos a tener un gran vínculo de amistad fecunda reafirmado por nuestra convivencia de vecinos, como ser algunos domingos que supo alegrarnos y bendecirnos con su presencia al compartir algún asado al que lo invité. Me acuerdo con humor que a veces él ingresaba urgentemente en nuestra casa con su vozarrón penetrante, alterando todo el contexto a su alrededor y manifestando sus inquietudes que podían ser de índole personal, como solicitar una máquina para afeitar en un día feriado o también de índole general, concernientes a situaciones con la comunidad, solicitando apoyo y colaboración.',
      "En una ocasión, durante una homilía de misa dominical, supo hacer notar a la feligresía la necesidad de conseguir colaboración para donar un secarropa a la vecina del frente (se refería a mi esposa, presente en la misa) por el ruido molesto que ocasionaba el aparato que teníamos en ese momento. Una principal característica en su vivir fue que siempre estuvo atento y dispuesto a las necesidades de la gente y siempre tuvo una respuesta y una solución a los distintos problemas por más complicados o imposibles de resolver que parecieran.",
      "El Padre Gandur fue siempre sensible a nuestras inquietudes, estando siempre dispuesto a atendernos por encima de sus necesidades personales. Para él no había horarios que no dedicara al servicio de las personas. Estas vivencias y muchas más compartidas con el Padre Gandur muestran solo una ínfima faceta de apreciación a su persona. Todas las obras que nos dejó son magníficas y fructíferas en beneficio de la comunidad y se pueden aprovechar y disfrutar hoy en día por todos.",
      "Lo que más deseo fervientemente es poder compartir mi más sincero y profundo agradecimiento al Padre Gandur. Aunque ya no está entre nosotros, nos sigue abrazando con su apoyo y calidez de amigo desde la Casa del Padre.",
    ],
    images: ["sanAntonio.jpg"],
  },
  {
    slug: "capilla-de-adoracion-perpetua",
    title: "Capilla de Adoración Perpetua Corazón Eucarístico de Jesús",
    author: "Adoradores del Santísimo Sacramento",
    category: "obras",
    content: [
      "El Padre Jorge Gandur tenía un profundo amor a la Eucaristía. Numerosos hechos de su vida lo unieron a ella. La tesis de su doctorado en Roma, providencialmente fue sobre la Eucaristía.",
      'Cuando el Padre Jorge vino a la entonces cuasi-parroquia de la Caridad, empezó su obra como torbellino que dejó como legado, entre otras cosas, siete capillas en puntos estratégicos. El Padre vio que en la platabanda de Av. Aconquija estaba la imagen de nuestra Madre la Virgen María, bajo la advocación de María Auxiliadora. Dijo: "aquí falta el Sagrado Corazón". pero por una cuestión de peso y tamaño, la imagen no pudo ser colocada sobre la platabanda. Unos operarios le dijeron: "Padre ese lote (señalando el actual emplazamiento de la Capilla de Adoración) está disponible". Tan rápido como era él, hizo la gestión inmediatamente y consiguió que ese mismo terreno fuera donado al Arzobispado. Allí se puso la imagen del Sagrado Corazón y poco tiempo después se construyó la capilla de la adoración perpetua. Allí había un pozo surgente de agua, signo de un profundo manantial de gracias. Parecía una metáfora de la fuerza de la Eucaristía con su gracia transformadora.',
      'En su afán de profundizar sobre la Eucaristía, en el año 2004 se comunicó con Mons. Puyelli, a quien le manifestó su deseo de tener una Capilla de Adoración Perpetua en su parroquia. Fue providencial que en ese momento estuviera con el Padre Patricio Hileman, misionero de Nuestra Señora del Santísimo Sacramento, quien de inmediato se puso a disposición y en diciembre de ese mismo año vino a catequizar a los fieles de la parroquia para organizar la Adoración Eucarística Perpetua. Apenas nueve meses más tarde, el 10 de septiembre de 2005, se inauguró la capilla. Tucumán ya contaba con el primer templo de Adoración Perpetua, al que el Padre Jorge le llamaba "la usina de amor" de su parroquia. El Padre nos decía: "el adorador debe ser un instrumento para cambiar la sociedad, pues enciende la temperatura espiritual del mundo. Con la inauguración de la capilla iniciamos un itinerario espiritual Eucarístico, con muchos frutos permanentes. Este itinerario presupone una gran humildad. Con la adoración perpetua, será posible perseverar y que otras generaciones continúen esta tarea hasta el fin de los tiempos."',
      "Próxima a cumplir 18 años, la Capilla de la Adoración Eucarística Perpetua es el valioso legado del querido Padre Jorge Gandur. Sus frutos son permanentes, diarios podríamos decir. Son abundantes los testimonios de piedad, de conversiones, de reconstrucciones familiares. El alcance de las gracias y favores recibidos por la Adoración al Santísimo es inconmensurable. ¡Gracias Padre Jorge por tan gran regalo!",
    ],
    images: ["oratorio2.jpg", "oratorio1.jpg", "sacerdote13.webp"],
  },
  {
    slug: "la-capilla-nuestra-senora-del-rosario",
    title: "La Capilla Nuestra Señora del Rosario de San Nicolás",
    author: "Miguel Moreno y Comunidad",
    category: "obras",
    content: [
      "En el año 1995 la Municipalidad de Yerba Buena anunció a los vecinos la disponibilidad de un terreno en Calle Salas y Valdez 102. El proyecto municipal contemplaba la construcción de un dispensario o una plaza, a consideración del vecindario. Puesto al tanto de la situación, nuestro párroco de aquel entonces, el padre Jorge Gandur, con el apoyo de los vecinos, consiguió modificar el proyecto municipal y adquirir el terreno para construcción de una Capilla.",
      "Inmediatamente el Padre Jorge Gandur, creó la comisión pro-templo, integrada por Pocha Ortiz, Ana Fernández, Francisca de la Puente, Antonio Almaraz y su esposa, Daniel Franchello y su esposa.",
      "En 1997 se dio comienzo a los trabajos de construcción. Para reunir los fondos necesarios se pensó una colecta de contribuyentes fijos a cargo de la Sra. Ana Fernández, quien además se ocupaba de organizar ferias de platos, sorteos, rifas y bingos en las instalaciones de la Escuela Mate de Luna, con el apoyo incondicional de la Srta. Ana de la Puente, todo bajo la atenta supervisión y colaboración del P. Jorge. Entre los varios contribuyentes cabe destacar el papel de la Sra. de Andreozzi y el Sr. Alvarez (quien donaba áridos y otros materiales).",
      "Con el correr del tiempo y el avance de la obra, el Padre Gandur comenzó a celebrar las primeras misas. A medida que se sucedían las celebraciones se fue notando la mayor afluencia de gente y, por lo tanto, hubo más colaboradores mensuales. Otras familias, motivadas por el Padre Jorge, se sumaron a las colaboraciones.",
      "Entre las personas que se incorporaron entonces estaban Juan Carlos D'Andrea y Sra. quienes con su hijo arquitecto, propusieron al P. Jorge la modificación del plano original. Se diseñó así un proyecto de líneas modernas que nuestro Párroco en ese momento aceptó con agrado.",
      "El Sr. D'Andrea, logró ampliar la cantidad de aportantes y la obra cobró nuevos impulsos y financiamiento, de modo tal que llegó a concluirse a fines de 2005, aproximadamente.",
      "Más adelante se concretó la adquisición de lo que actualmente conocemos como La Casita de La Virgen, en la que reside nuestro Vicario, el Padre Guillermo Benzi.",
      "El Padre Gandur, con su personalidad, lograba motivar a las personas para que abracen la fe en la Santísima Trinidad y en culto a la Sagrada Eucaristía. Son innumerables los frutos de conversión que se produjeron entre los vecinos del barrio de la Capilla Nuestra Señora del Rosario.",
      "Es de destacar también la gran obra humanitaria del P. Jorge para con el Padre Guillermo Benzi a quien acogió con tanto amor y lo ayudó permanente a sobrellevar su situación de salud.",
      "El Padre Gandur fue un cura que daba todo su tiempo, sus horas y horas de oración, el apoyo anímico y material para ayudar a sus hermanos sacerdotes y a toda persona que se arrimaba a él con alguna necesidad.",
      "Toda la comunidad de la Capilla de la Virgen del Rosario lo recuerdan con mucho amor y le agradecerán eternamente su obra que continúa dando frutos espirituales de conversión y crecimiento en la fe.",
      "Un fuerte abrazo al cielo al querido Padre Jorge Gandur.",
    ],
    images: ["rosario.jpg"],
  },
  {
    slug: "la-capilla-divino-nino",
    title: "La Capilla Divino Niño",
    author: "Julio Rossi",
    category: "obras",
    content: [
      "Conocí al padre Jorge en Semana Santa del 2000. Una amiga en común nos presentó. Un mes después, lo llamé para ofrecerme a colaborar en sus obras con los más necesitados.",
      "Recuerdo que pasé por la iglesia de la Caridad a buscarlo. Me indicó ir hasta el Barrio Nicolás Avellaneda IV, donde me mostró el centro parroquial de la Divina Misericordia. Allí funcionaba un comedor infantil, al lado de la capilla.",
      "Luego me pidió ir hacia el sur, bordeando el canal del Camino del Perú. Llegamos a un asentamiento muy humilde, llamado 2 de Septiembre. Tiempo después me enteré que el propio padre Jorge había pedido expresamente al Arzobispado, que ese sector olvidado, perteneciente al departamento Capital, fuera incorporado a los límites de la parroquia, para poder intervenir allí.",
      'Entrando por una calle llena de barro, llegamos a un pequeño predio con paredes a medio construir. Entonces me dijo: "¿Has visto aquel centro del Nicolas IV, con comedor, salones y capilla? Bueno, aquí quiero hacer lo mismo...y vos serás quien lo dirija." Ese estilo audaz, directo, seguro, me cautivó de inmediato. Yo ni siquiera asistía a misa los domingos. Casi sin conocerme, el padre Jorge me había encargado tamaña tarea.',
      'En esos días descubrí el concepto de la Divina Providencia. "¿Para qué te preocupas por las cosas materiales? Si estás trabajando para el Señor, Él se encargará de conseguir todo. Vos dale para adelante", me decía.',
      "En agosto del 2000 empezamos a dar almuerzo a los chicos del asentamiento. Durante la crisis del 2001/02, llegamos a alimentar a diario a más de 600 niños y ancianos entre ambos comedores, sin ninguna ayuda ni plan del Estado.",
      "Cada día, junto a los voluntarios del comedor, asistíamos a pequeños milagros. Como cuando le conté al padre Jorge que teníamos problemas para conseguir carne. Al día siguiente me llamó un funcionario del SENASA para donarnos 8 medias reses que habían sido confiscadas.",
      "Un día del año 2002, llegó el padre al comedor con una imagen del Divino Niño que le habían traído desde Perú. Acababa de ser restaurada porque en la aduana le habían roto los bracitos en busca de drogas. Fiel a su estilo, el padre nos pidió que nos pongamos en oración, a fin de conseguir los terrenos que daban hacia el canal, para construir allí la futura Capilla.",
      "A una familia que vivía precariamente en uno de los terrenos, le construimos una casita de material en otro sector del barrio. Y compramos la posesión a su vecino, un hombre evangelista, que no quería saber nada con vender su lote para que se hiciera una iglesia católica. Nunca el padre Jorge mostraba preocupación, como sabiendo que las cosas se solucionarían sí o sí. Solo nos pedía oración y confianza.",
      "En unos meses comenzaron las obras. Todo, como siempre, a pulmón, sin presupuesto, en manos del Señor. En menos de 4 meses se celebró la primera misa. Y en poco más de un año, estuvo terminado el templo.",
      "Ya para ese entonces, mi conversión había sido muy fuerte. Y el padre Jorge me había nombrado como Ministro de la Comunión, un servicio que me permitió acercar a Cristo a muchos enfermos de la parroquia. El ejemplo del padre Jorge Gandur, su coherencia de vida, su estilo tan personal de anunciar a Cristo mediante sus obras, me marcaron para siempre.",
    ],
    images: ["divino.jpg", "divino2.jpg"],
  },
  {
    slug: "un-sueno-por-cumplir",
    title: "Un sueño por cumplir",
    author: "Arq. Carlos Carrizo",
    category: "obras",
    content: [
      "Este proyecto fue solicitado por el Párroco Horacio Gómez, en respuesta a un viejo deseo del Padre Jorge Gandur, de construir un templo Parroquial más amplio y cómodo que estuviera a la altura del crecimiento que había experimentado la comunidad religiosa de esta Parroquia.",
      'Por tal motivo nos avocamos a la tarea de desarrollar un proyecto que permitiera albergar a más de mil personas sentadas adentro del templo, y para ello se plantea una nueva edificación en el antiguo estacionamiento que se encuentra dentro del predio de la actual Parroquia La Caridad.',
      'El templo se organiza en base a una planta de "cruz latina", con una nave central y dos laterales, y otras dos perpendiculares conformando la forma en "cruz". En esa intersección se encuentra el altar, el cual se enfatiza además por la gran cúpula que le da mayor protagonismo y logra captar la atención del espectador desde cualquier punto del interior del templo.',
      "También se hizo hincapié en la iluminación natural y en los efectos que se puedan lograr a través de las aberturas del volumen.",
      "En cuanto a su aspecto exterior, se resolvió teniendo en cuenta el pedido explícito del Padre Jorge el cual nos transmitió siempre como inquietud y deseo.",
      "Este proyecto se encuentra completamente desarrollado y con documentación aprobada, y a la espera de contar con los fondos necesarios para dar lugar al comienzo de la construcción del mismo, cumpliendo asi con la voluntad transmitida por nuestro querido Padre Jorge de que la Sede Parroquial cuente con un templo acorde a la población religiosa que hoy convoca y a la grandeza y santidad de nuestro Padre del cielo.",
    ],
    images: ["sueño1.jpg", "sueño2.jpg"],
  },

  // ═══════════════════ TESTIMONIOS ═══════════════════
  {
    slug: "testimonio-del-padre-jorge-gandur",
    title: "Testimonio del Padre Jorge Gandur",
    author: "Dolores Perez de Gaseni",
    subtitle: "Ex integrante de Caritas Vecina de Famailla",
    category: "testimonios",
    content: [
      "Vienen a mi memoria, gratos recuerdos del Padre Jorge Gandur, en su paso por la ciudad de Famailla, como Párroco de la Iglesia Nuestra Señora del Carmen.",
      "Una de las cosas que quiero resaltar es que en su rol de Párroco de la Iglesia Nuestra Señora del Carmen, su tarea no paso desapercibida, todo lo contrario, le puso su sello de bondad, humildad y del entusiasmo que lo caracterizaba, integrándose rápidamente a la comunidad famaillence.",
      "Lo que recuerdo de él, fue que atrajo a los jóvenes a la Iglesia, que se habían alejado en los años previos a su llegada, realizando reuniones, fogatas, adoraciones nocturnas y caminatas por los barrios humildes de la ciudad.",
      "En mi rol de participante activa de Caritas, puedo mencionar el trabajo mancomunado que realizamos con el Padre Jorge, con campañas de recolección de alimentos y de ropa a las familias carenciadas de Famailla.",
      "Asimismo, destaco la importancia que le dio a los festejos de la Patrona de nuestro pueblo, la Virgen del Carmen, que cada 16 de Julio, convocaba a participar a la toda la comunidad católica, a demostrar su fe a la Virgen.",
      "Con su carisma e humildad, atrajo a los jóvenes a la Iglesia, lo que dio sus frutos, dado de esa camada de jóvenes, varios abrazaron la vocación del Sacerdocio y actualmente ejercen como tales.",
      "En síntesis, en Famailla, guardamos recuerdos imborrables del querido Padre Jorge Gandur.",
    ],
    images: ["sacerdote5.jpg"],
  },
  {
    slug: "cuanta-gratitud",
    title: "En memoria del Padre Jorge Gandur",
    subtitle: "Cuánta gratitud",
    author: "Grupo de oración Santa Teresita del Niño Jesús",
    category: "testimonios",
    content: [
      "Fue nuestro director espiritual y el de muchas almas. A través de su vida pudimos descubrir a Cristo. Mediante su obrar pudimos comprender cuánto amor a Jesús y a María había en su interior.",
      "Era un sacerdote comprometido, adorador en espíritu y en verdad. Fue instrumento fiel y dócil, incansable, porque Dios obraba en Él.",
      'Nos dejó como herencia su testimonio de vida virtuosa y sencilla. Nos dejó su amor a Jesús Eucaristía. Desde ese Amor pudo cumplir su sueño de dedicar dos oratorios de adoración eucarística perpetua, "usinas de Amor", como él decía, en donde nuestras almas encuentran consuelo y descanso, en donde se respira un pedacito de cielo y en donde somos abrazados por infinitas gracias y bendiciones. Supo vivir el día a día confiando en la Providencia Divina y en María Santísima. Su fe allanó el camino a muchísimas almas.',
      "Fue quien nos hizo creer, confiar y esperar, y quien nos impulsó con su alegría y sabiduría a ser portadores de bondad y misericordia.",
      "Nos guió y ayudó a abrir el corazón a la Presencia Viva de Cristo. Tenemos mucho para recordar, mucho para agradecer. Estará por siempre en nuestros corazones.",
    ],
    images: ["sacerdote12.jpg"],
  },
  {
    slug: "el-padre-jorge-gandur-y-cristo-hoy",
    title: "El Padre Jorge Gandur y Cristo Hoy",
    author: "Mauro Carlorosi",
    category: "testimonios",
    content: [
      "Soy el padre Mauro Carlorosi, sacerdote del Oratorio de San Felipe Neri, miembro de Cristo Hoy desde 1999. Conocí al padre Jorge cuando ayudaba con la catequesis en el barrio 2 de septiembre, en 1998 y 1999. Las clases se daban bajo una higuera y en casa de doña María. Me tocó fundirle una camioneta cuando me la prestó para ir llevando chicos. Fue él quien me presentó al padre Juan Eduardo Arnau, para trabajar en Cristo Hoy, a fines de 1999.",
      'Al sacerdote serio, distante, formal que tenía en mente como padre Gandur, de a poco lo fui "perdiendo" por el real: alegre, jocoso, extrovertido, de desconcertante y potente voz, afable, inquieto, desinhibido… me rompió los esquemas y, de buenas a primeras, me fascinó el contraste.',
      "Sin embargo, pese a esto, era sumamente profundo en sus reflexiones, capaz de gran intimidad con el Señor en la oración y de un afán constante para hallar tiempo para la oración. Muchas veces al visitarlo lo encontrábamos simplemente rezando. Cuando nos trataba parecía que tenía tiempo para todo, siempre dispuesto y ocurrente, que le encantaba bromear y aconsejar en todo tipo de temas, de su especialidad o también en los que ignoraba… Y más aún, era así de alegre pese a estar soportando duras situaciones, presiones y cruces.",
      "Con mucho interés en la formación, no dejaba de leer, de citar libros y prestármelos. Como encargado de las páginas de espiritualidad, el padre poseía una pluma suave, profunda que acompasaba lo teológico con la exquisitez de un padre que habla a sus hijos. En la redacción del semanario se ocupaba de comentar asuntos muy variados. Eran muy graciosas las discusiones con el padre Arnau sobre los distintos temas. Coincidían en casi todo, y en lo que no, elípticamente se peleaban con bromas hasta terminar riéndose el uno con el otro. El padre Jorge no destacaba por sus propuestas de títulos para la tapa de Cristo Hoy pero sí en la prudencia con que se elegían los temas y noticias destacadas del entonces semanario.",
      'Cuando el padre Eduardo Arnau, fundador de Cristo Hoy, inició también la fundación de la comunidad del Oratorio de San Felipe Neri, el padre Jorge fue un compañero del itinerario. Hubo viajes, visitas, discernimientos fundamentales donde el padre Jorge no podía estar ausente, por su sabiduría, su prudencia y por su "curiosidad". Con el padre Eduardo, los dos adultos y de trayectoria, sin embargo, juntos, parecían compañeros de seminario que se divertían y hacían travesuras. Durante un encuentro internacional del Oratorio en Polonia ambos se habían "escapado" para poder descansar la siesta tucumana que en Europa no existía.',
      'El padre Jorge solía llamar por teléfono tanto a la parroquia del padre Eduardo y luego al Oratorio en Mercedes, Buenos Aires, y se hacía pasar por otra persona. Alguna vez se hizo pasar por un monseñor… Me hizo "meter la pata" una vez: había hablado con voz rara simulando ser otra persona pidiendo hablar con el padre Eduardo, le dije: "al padre Arnau lo mandamos a ordeñar las vacas…". Entonces, furioso, apareció la voz del padre Jorge: "¡te vamos a mandar a ordeñar las vacas a vos sinvergüenza!". A lo que respondí: "ah, es usted, ya le paso con el padre". A los pocos meses, en otra llamada por teléfono, volví a sentir la voz rara pidiendo por el padre Arnau. Pensé que era nuevamente el padre Jorge, entonces le dije: "¡al padre Arnau lo corrimos de la casa y los jóvenes tomamos el poder!" (con esto el padre Jorge saltaría hasta el techo). Pero no hubo más respuesta que un lamento: "¡Ay, no sabía!", dijo la voz al otro lado del teléfono. Entonces pregunté: "¿quién es?" Y una voz seria me dijo el nombre de un obispo. Sí, justo llamaba un obispo.',
      "Cada vez que lo recuerdo al padre Jorge, tanto en Cristo Hoy, como en su relación con el Oratorio no dejo de dar gracias a Dios por un personaje tan inusual, desopilante, profundo, que no tenía miedo de vestir como sacerdote, que amaba orar y que, en medio de sus propios combates, buscaba sinceramente a Dios.",
    ],
    images: ["amigos4.jpg"],
  },

  // ═══════════════════ MARIA ═══════════════════
  {
    slug: "charlas-de-consagracion-a-la-virgen",
    title: "El Padre Gandur y las charlas de Consagración a la Virgen",
    author: "Grupo Formador de las Charlas de Consagración para la Consagración al Inmaculado Corazón de María",
    subtitle: "José Asar, Javier Staffolani, María Victoria Mascaró de Paz, Adriana Rossi, Esteban Yranzo",
    category: "maria",
    content: [
      'El Padre Jorge Gandur fue un sacerdote que profesaba una especial devoción a la Santísima Virgen María. Todos recordamos su vozarrón inconfundible cantando: "Un día al cielo iré y la contemplaré."',
      "Ese gran amor a la Madre de Dios lo impulsó a promover, alentar y difundir la preparación de sus fieles para la Consagración al Inmaculado Corazón de María, como respuesta al pedido especial de Nuestra Señora en su aparición en Fátima, Portugal.",
      'Así fue que en el año 2006, en la Parroquia de la Caridad, nos convocó como laicos dedicados al Ministerio Mariano, para que diésemos las Charlas de Preparación para la Consagración al Inmaculado Corazón de María, a través del Método de San Luis María Grignon de Monfort con el lema "A Cristo por María, una entrega total". Es así que hasta la actualidad miles de almas se han consagrado a Nuestra Madre del Cielo, en una alianza de amor sagrada y perpetua.',
      "Los frutos de la Consagración Mariana, unidos a los de la Adoración al Santísimo Sacramento en la Capilla de Adoración Perpetua, se vieron en abundancia. Es que el Padre Jorge sabía, al igual que Don Bosco en su sueño, que los pilares para perseverar en el mar tumultuoso de éste mundo, debían ser María y la Eucaristía.",
      "Las Charlas de Consagración encendieron los corazones. Miles de consagrados dan testimonio hoy de conversiones, familias enteras consagradas como faros de luz, almas piadosas en cenáculos o soldados de la Reina del Cielo empuñando el Santo Rosario trabajando todos para la Iglesia de Cristo.",
      'Gracias Padre Jorge por marcarnos el camino mariano. Hoy continuamos como Grupo Formador trabajando y cantando: "Un día al Cielo iré y la contemplaré"!',
    ],
    images: ["consagracion1.jpg", "maria1.jpg", "consagracion2.webp"],
  },
  {
    slug: "testimonio-virgen-de-la-eucaristia",
    title: "Testimonio del Padre sobre La Virgen de la Eucaristía",
    author: "Padre Jorge A. Gandur",
    category: "maria",
    content: [
      "Después de la celebración de la Santa Misa, un jueves 30 de Octubre de 2003, llegaron dos señoras a pedir la bendición del agua. A una de ellas la conocía, a la otra no.",
      "Luego de la bendición, le pregunté a María Victoria Herrera de Padrós, cuyo nombre y apellido desconocía totalmente, si en su dormitorio tenía una imagen de la Virgen guardada, y si alguien le impedía rendirle culto. La lleve a un salón contiguo a la capilla, y allí le explique, ya que las palabras no salían, como era el manto de la imagen, mostrándole otra imagen de la Santísima Virgen.",
      "Hay detalles de la conversación que no los tengo presentes, pero la Providencia Divina y no otra cosa, quiso preparar a algunas familiar a tener amor a la Eucaristía por medio de esta imagen.",
      "Aclaro que en ningún momento hubo visión, considero uqe ufe una iluminación intelectiva, sin ninguna otra cosa que ser instrumento para que esta imagen empezara a circular antes del Año Eucarístico.",
      "Agradezco la docilidad de esta persona y la buena voluntad de sus colaboradoras para propagar la devoción de la Madre de Dios que ha hecho tanto bien, y hace, a tantas almas.",
      "Hay una verdad, no interesa cual pueda ser la procedencia, sino, el bien que pueda hacer a muchos el culto a la Madre de Dios, que tiene al Niño que representa su cuerpo y las uvas, la sangre entregada por nosotros.",
      "¡Dios bendiga el amor a la Eucaristía por medio de María!",
    ],
    images: ["maria1.jpg"],
  },

  // ═══════════════════ GRUPOS ═══════════════════
  {
    slug: "accion-catolica",
    title: "Acción Católica: ¡Acción!",
    author: "¡Alabado sea Jesucristo!",
    category: "grupos",
    content: [
      "Su paso por nuestras vidas fue así, como su vida: una aventura de lo cotidiano.",
      "Pensar en aquellos tiempos: junta amigos, activa grupos de Whatsapp; y, sobre todo, dibuja una sonrisa en varias, ya no tan jóvenes caras… sonrisas que quedarán marcadas para siempre en mi corazón.",
      "La Acción Católica de jóvenes en la parroquia fue formada en sus comienzos por tres amigas: Mavalle, Guadalupe y Hortensia y fue por iniciativa de Pilar Izquierdo, nuestra Pilar … fiel servidora de Dios y amante de la Acción Católica.",
      "Hace ya 20 años atrás Pilar, aquellas tres amigas y el Padre Jorge tenían la primera reunión del grupo de jóvenes. En aquella reunión el Padre nos habló del pasaje del evangelio de la multiplicación de los panes y los peces; y nos dijo muy clarito que si las confianzas eran puestas en Jesús, aquellos panes y peces se multiplicarían…",
      "Pasó no mucho tiempo y el grupo de jóvenes empezó a crecer: llegaron Albertito, Josecito, Leandro, Machi, Mariana, Roque, Dolores, Juancho, Merchi, Joaco…. Y llegaron Juan Andrés, y Diegote, Berni… Laurita, Flor… y siguieron llegando Paula y Cintia… y Daniel, Caro, Pablito…. Y las melli y Agos y Mariano… y siguieron llegando… y no viene al caso seguir nombrando… porque fuimos bastantes y hoy todavía…",
      "No voy a contarles hoy de la Acción Católica sino del Padre Jorge en nuestra Acción Católica.",
      "Nos quiso desde aquella primera reunión, y no nos abandonó nunca.",
      "Cuando le dijimos que necesitábamos que nos guiara en nuestra formación, un día fue lo que tardó en ayudarnos. Trajo una carpeta, el Catecismo de la Iglesia Católica en partes y nos dijo: sus reuniones tienen que ser fructíferas. Estudien, conozcan la verdad, que no sea un club social. Que sea un grupo de amigos, pero con Cristo.",
      "Y nos vió con ganas no sólo de estudio, sino también de acción. Nos dijo la defensa de la vida es una Noble causa, que necesita de jóvenes valientes: defiéndanla. Por eso nos acompañó en nuestro estudio, defensa y lucha por la vida por nacer. Cómo amaba el Padre Jorge a los Niños por Nacer, cómo amaba la vida, con cuánta fuerza la defendía... con qué espíritu defendía la Verdad.",
      "El padre era también un enamorado de los jóvenes; eso nos hacía sentir cuando estaba con nosotros. No necesitaba pasar largas jornadas con nosotros, entraba la mayoría de los Lunes, en algún momento de nuestra reunión sin anunciarse. Él sabía que eso nos encantaba, descontracturaba la reunión; a veces se quedaba y nos daba una charla, otras sólo nos saludaba, nos pedía algún favor, nos hacía cantar ( le encantaba escucharnos cantar fuerte), le gustaba vernos en la misa de los lunes a las 20hs.",
      'Un día de todos los Santos irrumpió al final de la reunión en el salón. Para sorpresa nuestra no nos habló de la Santidad, sino sobre los fieles difuntos y nos dijo: " ustedes los jóvenes no piensan en la muerte, no tienen en cuenta la muerte como algo cercano. Si ustedes muriesen mañana, ¿qué tendrían para darle al Señor? ". Y empezó a preguntar en forma personalizada a algunos. Hasta que llegó a Javi.. ud qué tiene para darle al señor? Un rato después terminó la reunión.',
      'Al día siguiente, fiesta de los Fieles Difuntos, Javi golpeó en casa de los curas en San Antonio a las 3 de la tarde. Se confesó con el padre Carlos y se fue a jugar un partido de fútbol, que terminó con "ovaciones en el cielo". Ese día, Dios lo llamó a su encuentro, ese día Javi pudo decirle a Jesús: esto Señor …un corazón perdonado tengo para darte.',
      "Tenía ese don de decir una palabra y mover muchos corazones. A uno de nuestros jóvenes le dijo: ¿sabes lo que va a decir tu tumba? Aquí yace el que pudo ser y no fue. Aquellas palabras todavía hoy hacen eco en su corazón.",
      "Tenía otro don: conocía el espíritu inquieto de un joven. No nos dejaba perder el tiempo: que seamos catequistas, que nos formemos, que ayudemos en la preparación de la liturgia, que organicemos charlas y marchas por la vida, que hagamos el pesebre viviente, el vía crucis, que nos demos tiempo y seamos adoradores… que tengamos misa diaria… jajjajaja!!!!",
      'Si nos acercábamos con un nuevo proyecto, invento o experimento nos decía: "HAGAN". Era un convencido de que si las cosas prosperaban eran de Dios.',
      "Como sabía que no podía acompañarnos siempre en las reuniones le pidió a, su mano derecha y gran amigo, el padre Horacio que lo hiciera. El padre Horacio tiene eso que los jóvenes necesitan: la constancia!!!",
      "Los jóvenes salíamos del colegio, la facultad, o el club para encontrarnos en la parroquia que estaba siempre abierta para nosotros el Padre quería que esos salones sean nuestro hogar. Aquellos tiempos nos encontraron estudiando frente al sagrario, o mientras hacíamos la liturgia. Sabíamos que si estábamos ahí algo nuevo, divertido, importante podía pasar … muchas veces a cualquier hora pasaba el Padre en su camionetita… a veces supervisaba como iba la jornada, otras gritaba si había alguien que lo acompañe … y ese, terminaba en un bautismo, dando alguna charla o sosteniendo algún micrófono. en algún lado, otras tocaba bocina en alguna de nuestras casas pidiendo películas… pero sanas, que no tengan ninguna porquería, decía!",
      "Hoy no puedo ir siempre a la parroquia, no puedo ayudar al padre Horacio mucho más que con la oración.",
      "Pero doy gracias a Dios de aquellos jóvenes felices viejos tiempos, que me ayudaron a encontrar amigos en Cristo, un esposo que busca la santidad, donde pude compartir con aquellos santos silenciosos como Josecito, o Pilar.",
      "Piedras, hondas y cascotes, pedregullos y algo más… son los jóvenes de la Acción Católica que me gusta pastorear…",
      "¡Si alguien sabía hacer de lo ordinario algo extraordinario, era Nuestro querido Padre George… si alguien sabía acercar Jóvenes a Jesús ese era nuestro querido Padre George!!!!",
    ],
    images: ["ac1.jpg", "ac2.jpg", "ac3.jpg", "ac4.jpg", "ac5.jpg"],
  },
  {
    slug: "la-orquesta-del-divino-nino",
    title: "El Padre Jorge Gandur y la Orquesta del Divino Niño",
    author: "Marcelo Ruiz",
    category: "grupos",
    content: [
      "Hace 16 años fui a tocar el violín a los niños de catequesis de la capilla del Divino Niño. Una nena me preguntó... ¿Cómo hago yo para aprender?",
      "Fue quien me hizo preguntarme también cómo podía hacer ... Presentándome primero ante el cura párroco... Pidiendo permiso.... El Padre Jorge me miró... Se dio la vuelta... Y regreso con unas llaves. Me dijo: -Arrancá....",
      "Un día, tiempo después, fui a visitarlo para decirle que quería abandonar el proyecto de la orquesta... dejar el Divino... Y con ese gran vozarron suyo inolvidable me respondió: -¡Parece que vos no sabés lo que hacés! ¿Lo sabés??",
      "-Enseño violín, padre, le dije.",
      "-Noooooo, me respondió. Estás haciendo tu apostolado. Andate...y no me dejés de hacer lo único que sabés hacer....",
      "Nunca más renuncie...y aprendí esa gran palabra: apostolado.... El granito de mostaza....",
      "La Orquesta del Divino Niño sigue. Tenemos tiempos duros, pero también alcanzamos grandes logros porque tenemos una gran ayuda desde el cielo. Porque el padre Jorge amaba la música y amaba a los niños.",
      "La cultura es algo muy necesario. No hace falta cárceles más grandes. Hace falta iniciar a los niños en la gran tradición musical y cultural.",
      "La pobreza más grande es ser nadie. Un artista tiene el aplauso, el reconocimiento...y eso lo vuelve ser diferente.",
      "La música… Es lo único q entra por el oído y llega al corazón.",
      "Con este apostolado, gracias al apoyo del padre Jorge, empezamos una tarea grande y hermosa. Empezamos a trabajar codo a codo con el encargado en ese momento del comedor Divino Niño, Julio Rossi. Comenzamos a poner la base de lo que debería ser acrecentar la cultura... La orquesta se fue poblando de alumnos de todos lados, de San Miguel y de Yerba Buena, de Cruz Alta y de Famaillá.... y se dan posibilidades de acercarse a todos. Con un solo requisito: amar la música y perseverar...",
      "La Orquesta Divino Niño tuvo grandes logros y su influjo se ha multiplicado en la Escuela Municipal Abejas, en la Casa de la Cultura del Nicolás, en el penal de Villa Urquiza (único penal en el país que cuenta con orquesta).",
      "La semilla que sembró el gran cura Gandur continua... Me empuja desde el cielo a seguir con mi apostolado.",
    ],
    images: ["orquesta1.jpg"],
  },
];
